title: Cake Wallet Guides
description: Cake Wallet guides and support resources
theme: just-the-docs

url: https://cake-tech.github.io/cakewallet-guides

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

plugins:
  - jekyll-default-layout
  